language: java

cache:
  directories:
    - $HOME/.m2

install:
  - java -XX:+PrintFlagsFinal -version
  - mvn --version
  - mvn dependency:resolve-plugins -DexcludeArtifactIds=plexus-component-metadata --update-snapshots -e
  - mvn dependency:resolve --update-snapshots -e

script: mvn clean verify --update-snapshots -e

jdk: oraclejdk7
